// app/subscribers/layout.js
import Navbar from "@/components/admin/Navbar";

export const metadata = {
  title: "Speak App",
  description: "Generated by WebDev",
};

export default function SubscribersLayout({ children }) {
  return (
    <div>
      <Navbar />
      <main>{children}</main>
    </div>
  );
}
