// app/admin/layout.js
import { currentUser } from "@clerk/nextjs/server";
import Navbar from "@/components/admin/Navbar";

export const metadata = {
  title: "Speak App",
  description: "Generated by WebDev",
};

export default async function AdminLayout({ children }) {
  return (
    <div>
      <Navbar />
      <main>{children}</main>
    </div>
  );
}
