import Navbar from "@/components/navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Speak App",
  description: "Generated by WebDev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
